### ISSUE TITLE
any interest in guidelines for contributors?

### ISSUE THREAD

**Issue by lpmi-13** [OWASP/owasp.github.io#73] opened 2020-03-21 19:42 UTC
I notice there is no CONTRIBUTING.md for the repo, and contributors may not know how best to go about submitting questions/PR's to the project.

I would be very interested in collating resources like these (to possibly include a "getting started" section in the README), if there's interest.

However, I'm aware that it might not be a current priority for the OWASP team.

Thought I'd ask just in case.

**Comment by kingthorin** [comment] 2020-04-25 00:58
This seems to be a duplicate of https://github.com/OWASP/owasp.github.io/issues/44

**Comment by lpmi-13** [comment] 2020-04-27 06:21
ah yes, it is. If there's any interest, I can work something up, otherwise suggest just closing both.

**Comment by hblankenship** [comment] 2021-09-30 15:02
Updated per 44

**Closed by hblankenship** 2021-09-30 15:02 UTC
Labels: enhancement
